### ISSUE TITLE
Can't seem to extract any data from the example

### ISSUE THREAD

**Issue by OhBehive** [dxFeed/dxfeed-python-api#17]
hey guys, been following the sample but I'm not getting any data. Column names in the dataframe seem fine. Anything I'm doing wrong?

> from dxfeed.core import DXFeedPy as dxc
import time  # for timed suscription
con = dxc.dxf_create_connection('demo.dxfeed.com:7300')
sub = dxc.dxf_create_subscription(con, 'Trade')
dxc.dxf_attach_listener(sub)
dxc.dxf_add_symbols(sub, ['AAPL', 'MSFT'])
sub.get_data()
dxc.dxf_detach_listener(sub)
df1 = sub.to_dataframe()
df1.head()
print(df1)

**Comment by iamishalkin** [comment]
Hello. First of all, this is a so-called stream subscription, so if there are no trades on stock exchanges, the endpoint (demo.dxfeed.com:7300) won't get any events and you will not get any either. It is also important to mention, that the demo endpoint provides delayed data, so if trades begin at 12:00 you will start receiving events at 12:30.
You may use a timed subscription from 0.3.0 release to get historical events. (See https://github.com/dxFeed/dxfeed-python-api/blob/0.3.0/examples/SubscriptionExample.ipynb)
Secondly, the get_data method and get_list method in the latest releases clear internal data structures. So, do not call this method if you don't need to get a list of events. You may also create dataframe before detaching the listener.

**Comment by Carlososuna11** [comment]
> Hello. First of all, this is a so-called stream subscription, so if there are no trades on stock exchanges, the endpoint (demo.dxfeed.com:7300) won't get any events and you will not get any either. It is also important to mention, that the demo endpoint provides delayed data, so if trades begin at 12:00 you will start receiving events at 12:30.
> You may use a timed subscription from 0.3.0 release to get historical events. (See https://github.com/dxFeed/dxfeed-python-api/blob/0.3.0/examples/SubscriptionExample.ipynb)
> Secondly, the get_data method and get_list method in the latest releases clear internal data structures. So, do not call this method if you don't need to get a list of events. You may also create dataframe before detaching the listener.

I have the same problem, try to test what you mention and still have no solution. Any solution?

**Comment by alimantu** [comment]
Hi,

Thank you for reaching us guys. Few things you could start with:
1. Because you're using stream subscription - you are getting events only during trade session, so it's kinda "live-subscription". Here you can check for trading hours of NASDAQ market for example.
2. Also because it's "live-subscription", some time should pass between connection and getting first event. Even AAPL don't have such great amount of trades per session to be able to fit few of them to the small time window between interpretation of the two commands by Python interpreter. 
3. It's not obligatory to create default event handler and attach it to the subscription manually. Our API behave so by default, so you can just skip this step.

Also please check step-by-step examples from attach.
[PythonAPI example.zip](https://github.com/dxFeed/dxfeed-python-api/files/4824006/PythonAPI.example.zip)

**Comment by alimantu** [comment]
@OhBehive can you please actualize the state of the issue? Are you still facing the problem?

**Comment by OhBehive** [comment]
Hi alimantu!

Thanks, I got it working.
